# Week 04 tutorial

#### if statements

In [167]:
x = 2
y = 2

if x == y:
    print('In block 1')
    print('They are equal!')

elif x > y:
    print('In block 2')
    print('x is more than y')

else:
    print('In block 3')
    print('y is more than x')

In block 1
They are equal!


### for loops

In [168]:
# Define list of numbers
num_list = list(range(10))
print('num_list = ', num_list)



num_list =  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [171]:
# Print these numbers one by one 
for n in num_list:
    print('->', n)  
    print(n*2)

-> 0
0
-> 1
2
-> 2
4
-> 3
6
-> 4
8
-> 5
10
-> 6
12
-> 7
14
-> 8
16
-> 9
18


In [172]:
dna = 'AACTTGGTTAAATTATGGG'
type(dna)

str

In [175]:
for c in dna:
    print('->', c, end=" ")

-> A -> A -> C -> T -> T -> G -> G -> T -> T -> A -> A -> A -> T -> T -> A -> T -> G -> G -> G 

In [176]:
dna

'AACTTGGTTAAATTATGGG'

In [177]:
dna_list = []
for c in dna:
    dna_list.append(c)
print('dna_list =', dna_list)

dna_list = ['A', 'A', 'C', 'T', 'T', 'G', 'G', 'T', 'T', 'A', 'A', 'A', 'T', 'T', 'A', 'T', 'G', 'G', 'G']


In [178]:
name = "Grimes"
simple_list = [c for c in name]
print('simple_list = ', simple_list)

simple_list =  ['G', 'r', 'i', 'm', 'e', 's']


In [181]:

name = "cam"
i = 0
for character in name:
    print(f"The letter is {character} and the index is {i}")
    i += 1 

The letter is c and the index is 0
The letter is a and the index is 1
The letter is m and the index is 2


In [182]:
# Alternate way with enumerate: 
for i, c in enumerate(name):
    print(f"name[{i}] = {c}")


name[0] = c
name[1] = a
name[2] = m


In [183]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


### while loops


In [185]:
i = 1
n = 10
while (i <= n):
    print(i)
    i = i + 1
   

1
2
3
4
5
6
7
8
9
10


### vectorised computations 

In [186]:
import numpy as np
N = 100
ns = np.arange(N)
ns

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [187]:
x = ns + 5  # add 5 to each element without having to loop through 
x

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104])

In [188]:
ns * 2  # multiply each element by 2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [189]:
ns.sum(), ns.max(), ns.min(), ns.argmax()

(4950, 99, 0, 99)

### functions

The simplest form of a function is just a block of code that we might want to use several times without typing it all out again.

In [190]:
# Function "Definition"
def my_function():
  print("Hello from a function") 

In [191]:
# Calling a function: 
my_function()
my_function()

# note that nothing goes in the brackets.

Hello from a function
Hello from a function


We can also give the function information (as "arguments") so it can do something with it. 

In [197]:
def say_hello(name = "everyone"):
    greeting = "hello " + name
    print(greeting)


In [198]:
say_hello("BINF")

hello BINF


In [199]:
say_hello()

hello everyone


How can we avoid this failing?

In [206]:
a = 5 
b = 1 

def add_two_numbers(x1, x2):      # "declaration" tells us: function's name, what it takes in (arguments), what it spits back (return)
    a = 2
    x = a + b            # "return" line: sends back the result so that we can do `something = func(a, b)`
    return x 


print(add_two_numbers(4, 3)) # what will this give?

3


In [ ]:
add_two_numbers(a, b) # add_two_numbers(5, 1)

In [209]:
# variable names 
x = "hello"
def f():
    x = "different value"
    print(x) 

f() 
# what will be output?

different value


In [210]:
x # ?

'hello'

#### Factorial example

In [218]:
# The function definition:
def n_factorial(n): 
    # Check that n is of the right type and form
    assert isinstance(n, int), 'Input is not an integer'
    assert n >= 0, 'Input needs to be positive'
    assert n <= 1000, 'Intput is too large!'

    # Initialize return variable
    val = 1

    # Loop over n
    for i in range(1, n+1):
        val *= i

    return val


In [213]:
n_factorial(1001)

AssertionError: Intput is too large!

In [215]:
n_factorial(5)

120

In [216]:
i # ?

11

In [ ]:
n_factorial(10)

In [ ]:
i # ?

In [ ]:
n_factorial(0)

In [ ]:
i # ?

In [ ]:
n_factorial(10001)

### Command line input

In [ ]:
import sys
print('Number of arguments:', len(sys.argv), 'arguments.')
print('Argument List:', str(sys.argv))

### Reading / writing files

In [ ]:
f = open("DatasaurusDozen.txt", "r")
print(f.readline()) # per line
f.close()


In [ ]:
f = open("DatasaurusDozen.txt", "r")
print(f.read()) # whole document 
f.close()

In [ ]:
# Question: what if we moved the text file to a different directory?

In [ ]:
# Improvement to opening files .. 

### Reading files with pandas

In [ ]:
import pandas as pd
df = pd.read_csv('data.csv')
#print(df.to_string())

In [ ]:
df_js = pd.read_json('data.json')
print(df_js.to_string())

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:

new_df = df.dropna()
df.dropna(inplace = True) # replaces within the same dataframe

In [ ]:
df.tail()

In [ ]:
# Drop rows if a particular set of columns have missing values
df.dropna(subset=['Date'], inplace = True)

In [ ]:
df.fillna(130, inplace = True) # replace NAs with fill value
df["Calories"].fillna(130, inplace = True) # replace values in the column "Calories" with fill value 
x = df["Calories"].mean()
df["Calories"].fillna(x, inplace = True) # replace with mean

In [ ]:
#df['Date'] = pd.to_datetime(df['Date'], format="mixed", yearfirst=True)   
#print(df.to_string())

In [ ]:
# Set values above a max to the max
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.loc[x, "Duration"] = 120

In [ ]:
# Drop rows with values above a max
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.drop(x, inplace = True)

In [ ]:
# Drop duplicate rows 
print(df.duplicated())
df.drop_duplicates(inplace = True)

## Biopython

In [ ]:
import Bio

In [ ]:
from Bio.Seq import Seq
my_seq = Seq("CATGTAGACTAG")

# print out some details about it
print("seq %s is %i bases long" % (my_seq, len(my_seq)))

### Reading and writing sequence files

In [ ]:
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

record = SeqRecord(
    Seq("MKQHKAMIVALIVICITAVVAALVTRKDLCEVHIRTGQTEVAVF"),
    id="YP_025292.1",
    name="HokC",
    description="toxic membrane protein, small",
)
print(record)
# As FASTA file 
Bio.SeqIO.write(record, "HokC.fasta", "fasta")

### Read in FASTA file

In [ ]:
filename = ? 

In [ ]:
from Bio import SeqIO
for record in SeqIO.parse(filename, "fasta"):
    sequence = record.seq


### Using E-utils

In [219]:
from Bio import Entrez
Entrez.email = "my.email@unsw.edu.au"
Entrez.tool = "my_script.py"

In [220]:
handle = Entrez.esearch(db="taxonomy", term="Human")
record = Entrez.read(handle)
record

{'Count': '1', 'RetMax': '1', 'RetStart': '0', 'IdList': ['9606'], 'TranslationSet': [], 'TranslationStack': [{'Term': 'Human[All Names]', 'Field': 'All Names', 'Count': '1', 'Explode': 'N'}, 'GROUP'], 'QueryTranslation': 'Human[All Names]'}

In [221]:
type(record)  # ?

Bio.Entrez.Parser.DictionaryElement

In [222]:
taxid = record['IdList'][0] # Now we have the taxid for human 

In [223]:
handle = Entrez.efetch(db="taxonomy", id=taxid, retmode="xml")
record = Entrez.read(handle)

In [224]:
record

[{'TaxId': '9606', 'ScientificName': 'Homo sapiens', 'OtherNames': {'Synonym': [], 'Includes': [], 'GenbankSynonym': [], 'GenbankAnamorph': [], 'EquivalentName': [], 'Acronym': [], 'CommonName': [], 'Misnomer': [], 'Misspelling': [], 'Inpart': [], 'Teleomorph': [], 'Name': [{'ClassCDE': 'authority', 'DispName': 'Homo sapiens Linnaeus, 1758'}, {'ClassCDE': 'misspelling', 'DispName': 'Home sapiens'}, {'ClassCDE': 'misspelling', 'DispName': 'Homo sampiens'}, {'ClassCDE': 'misspelling', 'DispName': 'Homo sapeins'}, {'ClassCDE': 'misspelling', 'DispName': 'Homo sapian'}, {'ClassCDE': 'misspelling', 'DispName': 'Homo sapians'}, {'ClassCDE': 'misspelling', 'DispName': 'Homo sapien'}, {'ClassCDE': 'misspelling', 'DispName': 'Homo sapience'}, {'ClassCDE': 'misspelling', 'DispName': 'Homo sapiense'}, {'ClassCDE': 'misspelling', 'DispName': 'Homo sapients'}, {'ClassCDE': 'misspelling', 'DispName': 'Homo sapines'}, {'ClassCDE': 'misspelling', 'DispName': 'Homo spaiens'}, {'ClassCDE': 'misspelling'

In [ ]:
first_result = record[0]

# If we had multiple results, we could loop through them
for result in record:
    print(result['Lineage'])

In [ ]:
print(first_result.keys())
print(first_result.values())

In [ ]:
print(first_result['ScientificName'])
print(first_result['Lineage'])

Cross ID search

In [ ]:
# Use Elink to find the assemblies for this taxid 

handle = Entrez.elink(dbfrom="taxonomy", db="assembly", from_uid=taxid)
links = Entrez.read(handle)

# we are searching the "assembly" database using the tax id.  So we might get multiple results.

In [ ]:
# How many results did we get?
len(links[0]['LinkSetDb'][0]['Link'] ) 


In [ ]:
# Let's look at the first result 
# (note that many databases are not 1:1)

In [ ]:
assembly_id = links[0]['LinkSetDb'][0]['Link'][0]['Id']
handle = Entrez.efetch(db="assembly", id=assembly_id, retmode="xml")
record = Entrez.read(handle)
print(record)

Let’s use the taxid ID to search for other database entries, and once again select the first ID.

In [ ]:
handle = Entrez.elink(dbfrom="assembly", db="nuccore", from_uid=assembly_id)
links = Entrez.read(handle)
nuc_id = links[0]['LinkSetDb'][0]['Link'][0]['Id']
handle = Entrez.efetch(db="nuccore", id=nuc_id, retmode="xml")
record = Entrez.read(handle)
print(record)

You can refine your queries by selecting certain fields aswell. For example, this search looks for organisms with the human taxid, and filters on “RefSeq” entries and with the word “CYBB” in the record title.

In [ ]:
handle = Entrez.esearch(db="nuccore", term="txid"+str(taxid)+"[Organism] AND refseq[filter] AND CYBB[title]")
record = Entrez.read(handle)
nuc_id = record['IdList'][0]
handle = Entrez.efetch(db="nuccore", id=nuc_id, retmode="xml")
record = Entrez.read(handle)
print(record)

In [ ]:
len(record)

## Functions challenge exercise

In [ ]:
# Count vowels in a string
string = "hello, how are YOU today?"
